baseURL = 'https://docs.parmin.cloud/'
languageCode = 'fa-IR'
title = 'مستندات پارمین'

enableEmoji = true
defaultContentLanguage = "fa"
[languages]
  [languages.fa]
    weight = 1
    languageName = "فارسی"
    languageDirection = "rtl"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[params]
  google_fonts = [
    ["Vazirmatn", "100, 200, 300, 400, 600, 700, 800, 900"],
    ["Fira Code", "500, 700"]
  ]
  sans_serif_font = "Vazirmatn"
  secondary_font  = "Vazirmatn"
  mono_font       = "Fira Code"
  [params.footer]
    copyright = "© :YEAR: تمامی حقوق برای شرکت پردازش ابری پارمین (پارمین کلود) محفوظ است."
    version = false

  [params.social]
    github = "ParminCloud"
    instagram = "parmin.cloud"
    rss = true


  [params.docs]
    title           = "مستندات پارمین"
    themeColor      = "cyan"
    darkMode        = true
    prism           = true
    prismTheme      = "lotusdocs"
    repoURL         = "https://github.com/ParminCloud/docs.parmin.cloud"
    repoBranch      = "master"
    editPage        = true
    lastMod         = true
    lastModRelative = true
    sidebarIcons    = true
    breadcrumbs     = false
    backToTop       = true
    # ToC
    toc             = true
    tocMobile       = true
    scrollSpy       = true
    # front matter
    descriptions    = true
    titleIcon       = true
    # content navigation
    navDesc         = true
    navDescTrunc    = 30
    listDescTrunc   = 100
    # Link behaviour
    intLinkTooltip  = true
    extLinkNewTab   = true
    # logoLinkURL = ""

